<?php

namespace RRHHBundle\Repository;

/**
 * AreaTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaTrabajoRepository extends \Doctrine\ORM\EntityRepository
{


	/*
	* Listado Area de Trabajo
	*/
	public function getAreaTrabajo(){

		$em= $this->getEntityManager();       
     
        $dql = 'SELECT a.id, a.area FROM RRHHBundle:AreaTrabajo a ORDER By a.id ASC ';
        $dql = $em->createQuery($dql); 

        return $dql->getResult();        
	}
}
