<?php

namespace RRHHBundle\Repository;

/**
 * CategoriaOcupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaOcupRepository extends \Doctrine\ORM\EntityRepository
{


	/*
	* Listado Categoria Ocupacion
	*/
	public function getCategoriaOcupacion(){

		$em= $this->getEntityManager();       
     
        $dql = 'SELECT co.id, co.categoria , co.abr FROM RRHHBundle:CategoriaOcup co ORDER By co.id ASC ';
        $dql = $em->createQuery($dql); 

        return $dql->getResult();        
	}
}
