<?php

namespace RRHHBundle\Repository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends \Doctrine\ORM\EntityRepository
{


	/*
	* get max numero contrato
	*/
	public function isNoContrato($id, $noC){

		$em= $this->getEntityManager();       
     
        $dql = 'SELECT c FROM RRHHBundle:Contrato c WHERE c.id NOT IN (:id) and c.noContrato=:noC';
        $dql = $em->createQuery($dql); 

        return $dql->setParameter('id', $id)->setParameter('noC', $noC)->getResult();        
	}

	
}
