<?php

namespace RRHHBundle\Repository;

/**
 * GrupoEscalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEscalaRepository extends \Doctrine\ORM\EntityRepository
{


	/*
	* Listado Grupo Escala
	*/
	public function getGrupoEscala(){
		$em= $this->getEntityManager();       
        $dql = 'SELECT ge.id, ge.grupo FROM RRHHBundle:GrupoEscala ge ORDER By ge.id ASC';
        $dql = $em->createQuery($dql);
        return $dql->getResult();        
	}
}
