<?php

namespace RRHHBundle\Repository;

/**
 * HorarioTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioTrabajoRepository extends \Doctrine\ORM\EntityRepository
{


}
