<?php

namespace RRHHBundle\Repository;

/**
 * JornadaTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JornadaTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
