<?php

namespace RRHHBundle\Repository;

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* Listado Municipios por provincias 
	*/
	public function getMunicipio(){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $provincia = 'SELECT p FROM RRHHBundle:Provincia p ORDER By p.id ASC';
        $provincia = $em->createQuery($provincia); 
        $provincia = $provincia->getResult();

        

        foreach ($provincia as $p) {
        	$municipio = 'SELECT m.id, m.municipio FROM RRHHBundle:Municipio m JOIN m.provincia p WHERE p.id=:idP ORDER By m.id ASC ';
        	$municipio = $em->createQuery($municipio);
        	$municipio = $municipio
        					->setParameter('idP', $p->getId())
        					->getResult();

        	$array[] = array(
        		'provincia'=> $p,
        		'municipio'=> $municipio
        	);
        }



        return $array;        
	}
}
