<?php

namespace RRHHBundle\Repository;

/**
 * NivelEscolarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelEscolarRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* Listado Nivel Escolar
	*/
	public function getNivelEscolar(){
		$em= $this->getEntityManager();      
        $dql = 'SELECT ne.id, ne.nivel , ne.abr FROM RRHHBundle:NivelEscolar ne ORDER By ne.id ASC ';
        $dql = $em->createQuery($dql); 
        return $dql->getResult();        
	}
	
}
