<?php

namespace RRHHBundle\Repository;

/**
 * PeriodicidadPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodicidadPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
