<?php

namespace RRHHBundle\Repository;

/**
 * SalarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarioRepository extends \Doctrine\ORM\EntityRepository
{
}
