<?php

namespace RRHHBundle\Repository;

/**
 * TipoInformacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInformacionRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* Listado Tipo de Contrato
	*/
	public function allFalse($contrato){
		$em= $this->getEntityManager();      
        $dql = 'UPDATE RRHHBundle:TipoInformacion ti SET ti.clasificada = 0 , ti.superior = 0, ti.regimenCerrado = 0 WHERE ti.contrato=:contrato ';
        $dql = $em->createQuery($dql); 
        return $dql->setParameter('contrato', $contrato)->getResult();        
	}
}
