<?php

namespace Proxies\__CG__\RRHHBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrato extends \RRHHBundle\Entity\Contrato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'id', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'noContrato', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'fecha', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'nombre', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'ci', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'sexo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'nivelEscolar', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'direccion', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'municipio', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'provincia', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'telefono', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'areaTrabajo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'tipoContrato', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'cargo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'categoriaOcupacional', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'grupoEscala', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'duracionContrato'];
        }

        return ['__isInitialized__', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'id', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'noContrato', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'fecha', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'nombre', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'ci', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'sexo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'nivelEscolar', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'direccion', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'municipio', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'provincia', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'telefono', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'areaTrabajo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'tipoContrato', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'cargo', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'categoriaOcupacional', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'grupoEscala', '' . "\0" . 'RRHHBundle\\Entity\\Contrato' . "\0" . 'duracionContrato'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contrato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi($ci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', [$ci]);

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', []);

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracionContrato($duracionContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracionContrato', [$duracionContrato]);

        return parent::setDuracionContrato($duracionContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracionContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracionContrato', []);

        return parent::getDuracionContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelEscolar(\RRHHBundle\Entity\NivelEscolar $nivelEscolar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelEscolar', [$nivelEscolar]);

        return parent::setNivelEscolar($nivelEscolar);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelEscolar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelEscolar', []);

        return parent::getNivelEscolar();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(\RRHHBundle\Entity\Municipio $municipio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia(\RRHHBundle\Entity\Provincia $provincia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaTrabajo(\RRHHBundle\Entity\AreaTrabajo $areaTrabajo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaTrabajo', [$areaTrabajo]);

        return parent::setAreaTrabajo($areaTrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaTrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaTrabajo', []);

        return parent::getAreaTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoContrato(\RRHHBundle\Entity\TipoContrato $tipoContrato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoContrato', [$tipoContrato]);

        return parent::setTipoContrato($tipoContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoContrato', []);

        return parent::getTipoContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo(\PiedraBundle\Entity\Cargo $cargo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', [$cargo]);

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', []);

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaOcupacional(\RRHHBundle\Entity\CategoriaOcup $categoriaOcupacional = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaOcupacional', [$categoriaOcupacional]);

        return parent::setCategoriaOcupacional($categoriaOcupacional);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaOcupacional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaOcupacional', []);

        return parent::getCategoriaOcupacional();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoEscala(\RRHHBundle\Entity\GrupoEscala $grupoEscala = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoEscala', [$grupoEscala]);

        return parent::setGrupoEscala($grupoEscala);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEscala()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEscala', []);

        return parent::getGrupoEscala();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoContrato($noContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoContrato', [$noContrato]);

        return parent::setNoContrato($noContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoContrato', []);

        return parent::getNoContrato();
    }

}
