<?php

namespace Proxies\__CG__\InformaticaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Movimiento extends \InformaticaBundle\Entity\Movimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'tipoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'tipoMovimiento', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'equipoOrigen', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'equipoDestino', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'pieza', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'inventario', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'factura', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'usuario', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'unidad', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'dictaminado', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'log'];
        }

        return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'tipoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'tipoMovimiento', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'equipoOrigen', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'equipoDestino', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'pieza', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'inventario', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'factura', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'usuario', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'unidad', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'dictaminado', '' . "\0" . 'InformaticaBundle\\Entity\\Movimiento' . "\0" . 'log'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Movimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactura($factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactura', [$factura]);

        return parent::setFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactura', []);

        return parent::getFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEquipo(\InformaticaBundle\Entity\TipoEquipo $tipoEquipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEquipo', [$tipoEquipo]);

        return parent::setTipoEquipo($tipoEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEquipo', []);

        return parent::getTipoEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoMovimiento(\InformaticaBundle\Entity\TipoMovimiento $tipoMovimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoMovimiento', [$tipoMovimiento]);

        return parent::setTipoMovimiento($tipoMovimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoMovimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoMovimiento', []);

        return parent::getTipoMovimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipoOrigen(\InformaticaBundle\Entity\Equipo $equipoOrigen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipoOrigen', [$equipoOrigen]);

        return parent::setEquipoOrigen($equipoOrigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipoOrigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipoOrigen', []);

        return parent::getEquipoOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipoDestino(\InformaticaBundle\Entity\Equipo $equipoDestino = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipoDestino', [$equipoDestino]);

        return parent::setEquipoDestino($equipoDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipoDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipoDestino', []);

        return parent::getEquipoDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setPieza(\InformaticaBundle\Entity\Pieza $pieza = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPieza', [$pieza]);

        return parent::setPieza($pieza);
    }

    /**
     * {@inheritDoc}
     */
    public function getPieza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPieza', []);

        return parent::getPieza();
    }

    /**
     * {@inheritDoc}
     */
    public function setInventario(\InformaticaBundle\Entity\InventarioEquipo $inventario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInventario', [$inventario]);

        return parent::setInventario($inventario);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventario', []);

        return parent::getInventario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDictaminado($dictaminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDictaminado', [$dictaminado]);

        return parent::setDictaminado($dictaminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getDictaminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDictaminado', []);

        return parent::getDictaminado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidad(\InformaticaBundle\Entity\Unidad $unidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidad', [$unidad]);

        return parent::setUnidad($unidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidad', []);

        return parent::getUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLog($log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLog', [$log]);

        return parent::setLog($log);
    }

    /**
     * {@inheritDoc}
     */
    public function getLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLog', []);

        return parent::getLog();
    }

}
