<?php

namespace Proxies\__CG__\RRHHBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormaPago extends \RRHHBundle\Entity\FormaPago implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'id', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'atiempo', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'arendimiento', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'porresultado', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'contrato'];
        }

        return ['__isInitialized__', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'id', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'atiempo', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'arendimiento', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'porresultado', '' . "\0" . 'RRHHBundle\\Entity\\FormaPago' . "\0" . 'contrato'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormaPago $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtiempo($atiempo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtiempo', [$atiempo]);

        return parent::setAtiempo($atiempo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtiempo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtiempo', []);

        return parent::getAtiempo();
    }

    /**
     * {@inheritDoc}
     */
    public function setArendimiento($arendimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArendimiento', [$arendimiento]);

        return parent::setArendimiento($arendimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getArendimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArendimiento', []);

        return parent::getArendimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorresultado($porresultado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorresultado', [$porresultado]);

        return parent::setPorresultado($porresultado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorresultado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorresultado', []);

        return parent::getPorresultado();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrato(\RRHHBundle\Entity\Contrato $contrato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrato', [$contrato]);

        return parent::setContrato($contrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrato', []);

        return parent::getContrato();
    }

}
