<?php

namespace Proxies\__CG__\InformaticaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ubicacion extends \InformaticaBundle\Entity\Ubicacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'idequipo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'entidad', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'areatrabajo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'puestotrabajo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'anotadoPor'];
        }

        return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'idequipo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'entidad', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'areatrabajo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'puestotrabajo', '' . "\0" . 'InformaticaBundle\\Entity\\Ubicacion' . "\0" . 'anotadoPor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ubicacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdequipo($idequipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdequipo', [$idequipo]);

        return parent::setIdequipo($idequipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdequipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdequipo', []);

        return parent::getIdequipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntidad($entidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntidad', [$entidad]);

        return parent::setEntidad($entidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidad', []);

        return parent::getEntidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreatrabajo($areatrabajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreatrabajo', [$areatrabajo]);

        return parent::setAreatrabajo($areatrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreatrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreatrabajo', []);

        return parent::getAreatrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuestotrabajo($puestotrabajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuestotrabajo', [$puestotrabajo]);

        return parent::setPuestotrabajo($puestotrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuestotrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuestotrabajo', []);

        return parent::getPuestotrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnotadoPor($anotadoPor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnotadoPor', [$anotadoPor]);

        return parent::setAnotadoPor($anotadoPor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnotadoPor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnotadoPor', []);

        return parent::getAnotadoPor();
    }

}
