<?php

namespace Proxies\__CG__\InformaticaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InventarioEquipo extends \InformaticaBundle\Entity\InventarioEquipo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'estadoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'pieza', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'equipo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'marca', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'modelo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'ctecnica', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'serial', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'baja'];
        }

        return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'estadoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'pieza', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'equipo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'marca', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'modelo', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'ctecnica', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'serial', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\InventarioEquipo' . "\0" . 'baja'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InventarioEquipo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', [$marca]);

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', []);

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', [$modelo]);

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', []);

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtecnica($ctecnica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtecnica', [$ctecnica]);

        return parent::setCtecnica($ctecnica);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtecnica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtecnica', []);

        return parent::getCtecnica();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial($serial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaja($baja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaja', [$baja]);

        return parent::setBaja($baja);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaja', []);

        return parent::getBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoEquipo(\InformaticaBundle\Entity\EstadoEquipo $estadoEquipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoEquipo', [$estadoEquipo]);

        return parent::setEstadoEquipo($estadoEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoEquipo', []);

        return parent::getEstadoEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPieza(\InformaticaBundle\Entity\Pieza $pieza = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPieza', [$pieza]);

        return parent::setPieza($pieza);
    }

    /**
     * {@inheritDoc}
     */
    public function getPieza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPieza', []);

        return parent::getPieza();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipo(\InformaticaBundle\Entity\Equipo $equipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipo', [$equipo]);

        return parent::setEquipo($equipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipo', []);

        return parent::getEquipo();
    }

}
