<?php

namespace InformaticaBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* Listado de Cargos
	*/
	public function getCargos(){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $cargos = 'SELECT c FROM InformaticaBundle:Cargo c ORDER By c.cargo ASC';
        $cargos = $em->createQuery($cargos); 
        $cargos = $cargos->getResult();
        return $cargos;        
	}
}
