<?php

namespace InformaticaBundle\Repository;

/**
 * ConexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConexionRepository extends \Doctrine\ORM\EntityRepository
{




	/*
	* Listado de Cargos
	*/
	public function getConexiones($unidad){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $conexion = 'SELECT c FROM InformaticaBundle:Conexion c WHERE c.unidad=:unidad';
        $conexion = $em->createQuery($conexion); 
        $conexion = $conexion->setParameter('unidad', $unidad)->getResult();

        $list = array();

        foreach ($conexion as $c) {
        	$password = base64_decode($c->getPassword());        	
        	$list[$c->getTipo()] = array(
        		'id' => $c->getId(),
        		'dirver' => $c->getDriver(),
        		'host' =>$c->getHost(),
        		'port' =>$c->getPort(),
        		'dbname' =>$c->getDbname(),
        		'user' => $c->getUser(),
        		'password' => $password
        	);



        }
        return $list;        
	}
}
