<?php

namespace InformaticaBundle\Repository;

/**
 * EquipoAprobadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoAprobadoRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* insertar equipoAprobado
	*/
	public function getTipoEquipoSinInsertar($unidad){

		$em = $this->getEntityManager();    

     
        $tipo = 'SELECT te FROM InformaticaBundle:TipoEquipo te WHERE te.id NOT IN (SELECT tee.id FROM InformaticaBundle:EquipoAprobado ea JOIN ea.tipoEquipo tee WHERE ea.unidad=:unidad )';
        $tipo = $em->createQuery($tipo); 
        $tipo = $tipo->setParameter('unidad', $unidad)->getResult();

        return $tipo;        
	}


}
