<?php

namespace InformaticaBundle\Repository;

/**
 * EquiposCuadradosAFTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoCuadradoAFTRepository extends \Doctrine\ORM\EntityRepository
{
}
