<?php

namespace InformaticaBundle\Repository;

/**
 * EstadoEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEquipoRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* Listado de Piezas 
	*/
	public function getEstados(){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $estado = 'SELECT ee FROM InformaticaBundle:EstadoEquipo ee ORDER By ee.id ASC';
        $estado = $em->createQuery($estado); 
        $estado = $estado->getResult();

        $estado = $this->listaString($estado);

        return $estado;        
	}



    /*
    * convierte arreglo en listata string para select
    */
    public function listaString($listado){

        $list = "{"; $cont = 0;
        foreach ($listado as $lista) {

            $cont++;
            if($cont == count($listado)){
                $list .= '"'.$lista->getId().'": "'.$lista->getEstado().'"}';
            }else{
                $list .= '"'.$lista->getId().'": "'.$lista->getEstado().'",';
            }            
         } 


        return $list;
    }


}
