<?php

namespace InformaticaBundle\Repository;

/**
 * EstadoMovimientoAFTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoMovimientoAFTRepository extends \Doctrine\ORM\EntityRepository
{
}
