<?php

namespace InformaticaBundle\Repository;

/**
 * InventariosPartesyPiezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioParteyPiezaRepository extends \Doctrine\ORM\EntityRepository
{
}
