<?php

namespace InformaticaBundle\Repository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* Listado de Moviemintos
	*/
	public function getMovimientos($baja, $unidad, $log){
		$em = $this->getEntityManager();    
		    
        $equipos = 'SELECT mov FROM InformaticaBundle:Movimiento mov 
        			   JOIN mov.equipoDestino ed 
        			   JOIN mov.unidad u
        			   WHERE ed.baja =:baja and mov.unidad=:unidad and mov.log=:log ORDER By mov.fecha DESC';
        $equipos = $em->createQuery($equipos); 
        $equipos = $equipos
                        ->setParameter('baja', $baja)
                        ->setParameter('unidad', $unidad)
                        ->setParameter('log', $log)
                        ->getResult();
        return $equipos;        
	}


        /*
        * actualizar variable log de los movimientos viejos con el mismo inventario que el que se va adicionar
        */
        public function updateLog($inventario){
                $em = $this->getEntityManager();    
                $mov = 'UPDATE InformaticaBundle:Movimiento m SET m.log=:log WHERE m.inventario=:inventario';
                $mov = $em->createQuery($mov); 
                $mov = $mov
                        ->setParameter('log', 0)
                        ->setParameter('inventario', $inventario)
                        ->getResult();
        return $mov;        
        }
}
