<?php

namespace InformaticaBundle\Repository;

/**
 * PartesyPiezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParteyPiezaRepository extends \Doctrine\ORM\EntityRepository
{
}
