<?php

namespace InformaticaBundle\Repository;

/**
 * PiezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiezaRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* Listado de Piezas 
	*/
	public function getPiezas(){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $pieza = 'SELECT p FROM InformaticaBundle:Pieza p WHERE p.id <> 0 ORDER By p.id ASC';
        $pieza = $em->createQuery($pieza); 
        $pieza = $pieza->getResult();

        return $pieza;        
	}


	/*
	* Listado de Piezas q faltan al equipo 
	*/
	public function getPiezasEquipoNoSelect($equipo){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $pieza = 'SELECT p.id, p.pieza FROM InformaticaBundle:Pieza p WHERE p.id <> 0  ORDER By p.id ASC';
        		//  AND p.id not in (SELECT pp.id FROM InformaticaBundle:InventarioEquipo ie JOIN ie.pieza pp WHERE ie.equipo=:equipo) ORDER By p.id ASC';
        $pieza = $em->createQuery($pieza); 
        $pieza = $pieza
        			//->setParameter('equipo', $equipo )
        			->getResult();

        return $pieza;        
	}


	
}
