<?php

namespace InformaticaBundle\Repository;

/**
 * ResponsablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableRepository extends \Doctrine\ORM\EntityRepository
{


	public function getResponsableDestino($id_responsable){
	$em = $this->getEntityManager();    

	$array = array();   
     
        $responsables = 'SELECT r.id, r.responsable, c.cargo, c.id id_cargo , l.local  FROM InformaticaBundle:Responsable r         			
        			JOIN r.local l
                                JOIN l.area a
                                JOIN r.cargo c
        			WHERE r.id <> ?1 ORDER By a.area ASC';
        $responsables = $em->createQuery($responsables); 
        $responsables = $responsables->setParameter(1, $id_responsable)->getResult();

        return $responsables;
	}


        /*
        * get Responsables del Local
        */
        public function getResponsables($id_local){

                $em = $this->getEntityManager(); 

                $responsables = 'SELECT r.id, r.responsable FROM InformaticaBundle:Responsable r                            
                                        JOIN r.local l
                                        WHERE l.id =:id_local ORDER By r.id ASC';
                $responsables = $em->createQuery($responsables); 
                $responsables = $responsables
                                        ->setParameter('id_local', $id_local)
                                        ->getResult();  

                return $responsables;     

        }


        /*
        * Listado de Responsable Ordenado por nombre
        */
        public function getResponsablesNombre(){

                $em = $this->getEntityManager();    

                $array = array();   
     
                $responsables = 'SELECT r FROM InformaticaBundle:Responsable r ORDER By r.responsable ASC';
                $responsables = $em->createQuery($responsables); 
                $responsables = $responsables->getResult();
                return $responsables;        
        }
}
