<?php

namespace InformaticaBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* Listado de roles
	*/
	public function getRoles(){

		$em = $this->getEntityManager();   
		
     
        $roles = 'SELECT r.id, r.name, r.role FROM InformaticaBundle:Rol r ORDER By r.id ASC';
        $roles = $em->createQuery($roles); 
        $roles = $roles->getResult();
        
        return $roles;  		      
	}

	
}
