<?php

namespace InformaticaBundle\Repository;

/**
 * SistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaRepository extends \Doctrine\ORM\EntityRepository
{
}
