<?php

namespace InformaticaBundle\Repository;

/**
 * SubLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubLocalRepository extends \Doctrine\ORM\EntityRepository
{



	/*
	* Listado de subArea del area
	*/
	public function getSubArea($area){

		$em = $this->getEntityManager();    

		$array = array();   
     
        $subarea = 'SELECT sub.id, sub.subLocal, l.local FROM InformaticaBundle:SubLocal sub JOIN sub.local l WHERE sub.local=:area ORDER By l.id ASC';
        $subarea = $em->createQuery($subarea); 
        $subarea = $subarea->setParameter('area', $area)->getResult();
        
        return $subarea;        
	}
}
