<?php

namespace InformaticaBundle\Repository;

/**
 * TipoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
