<?php

namespace InformaticaBundle\Repository;

/**
 * TiposEquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
