<?php

namespace InformaticaBundle\Repository;

/**
 * UbicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
