<?php

namespace InformaticaBundle\Repository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{


    /*
    * get usuarios
    */
    public function getUsuarios($unidad, $activo){
    	
    	if( $unidad != null && $activo!= null){
    		$em = $this->getEntityManager(); 
            $usuarios = 'SELECT u FROM InformaticaBundle:Usuario u  
                                    WHERE u.unidad=:unidad and u.active=:activo ORDER By u.name ASC';
            $usuarios = $em->createQuery($usuarios); 
            $usuarios = $usuarios
                            ->setParameter('unidad', $unidad)
                            ->setParameter('activo', $activo)
                            ->getResult();  
            return $usuarios;
    	}
    	else if( $unidad == null && $activo != null){
    		$em = $this->getEntityManager(); 
            $usuarios = 'SELECT u FROM InformaticaBundle:Usuario u  
                                    WHERE u.active=:activo ORDER By u.name ASC';
            $usuarios = $em->createQuery($usuarios); 
            $usuarios = $usuarios                                    
                            ->setParameter('activo', $activo)
                            ->getResult();  
            return $usuarios;

    	}
    	else if( $unidad != null && $activo == null){
    		$em = $this->getEntityManager(); 
            $usuarios = 'SELECT u FROM InformaticaBundle:Usuario u  
                                    WHERE u.unidad=:unidad ORDER By u.name ASC';
            $usuarios = $em->createQuery($usuarios); 
            $usuarios = $usuarios
                            ->setParameter('unidad', $unidad)                            
                            ->getResult();  
            return $usuarios;

    	}
    	else if( $unidad == null && $activo == null){
    		$em = $this->getEntityManager(); 
            $usuarios = 'SELECT u FROM InformaticaBundle:Usuario u ORDER By u.name ASC';
            $usuarios = $em->createQuery($usuarios); 
            $usuarios = $usuarios
                            
                            ->getResult();  
            return $usuarios;
    	}                
    }


    

    

	
}
