<?php

namespace InformaticaBundle\Repository;

/**
 * UsuarioRedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRedRepository extends \Doctrine\ORM\EntityRepository
{
}
