<?php

namespace PiedraBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository
{

	

	/*
	* obtener listado de cargos sin asignar
	*/
	public function getCargoSinAsignar(){

		$em= $this->getEntityManager();       
     
        $cargo_sinAsignar = 'SELECT c.id, c.cargo FROM PiedraBundle:Cargo c WHERE c.id NOT IN (SELECT c1.id FROM PiedraBundle:UsuarioDominio ud JOIN ud.cargo c1 WHERE ud.baja =:baja) ORDER By c.cargo ASC ';
        $cargo_sinAsignar = $em->createQuery($cargo_sinAsignar); 
        return $cargo_sinAsignar        			
        			->setParameter('baja', true)
        			->getResult();        
	}


	/*
	* Listado Cargos
	*/
	public function getCargos(){

		$em= $this->getEntityManager();       
     
        $dql = 'SELECT c.id, c.cargo FROM PiedraBundle:Cargo c ORDER By c.cargo ASC ';
        $dql = $em->createQuery($dql); 

        return $dql->getResult();        
	}
}
