<?php

namespace PiedraBundle\Repository;

/**
 * DepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentoRepository extends \Doctrine\ORM\EntityRepository
{



	 public function getInventarioNull($departamento){
        $em= $this->getEntityManager();

        $dql ='SELECT i FROM PiedraBundle:Inventario i WHERE i.departamento =:dept and i.pc is Null and i.baja =:false ';
        $inventario_null = $em->createQuery($dql);       

      
        return  $inventario_null
        				->setParameter('dept', $departamento)
        				->setParameter('false', 0)
        				->getResult();          

    }

    
    


    





	
}
