<?php

namespace PiedraBundle\Repository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoRepository extends \Doctrine\ORM\EntityRepository
{





	public function getDocumentosByOrganismo(){

		$em= $this->getEntityManager();

        $dql ='SELECT o FROM PiedraBundle:Organismo o';
        $organismos = $em->createQuery($dql); 
        $organismos = $organismos->getResult();
        $array = array();

        foreach ($organismos as $o) {

              $dql ='SELECT d FROM PiedraBundle:Documento d Where d.organismo=:o';
              $documentos = $em->createQuery($dql);
              $documentos = $documentos->setParameter('o', $o)->getResult();

             

              $array[] = array(
              		'o'=> $o,
              		'documentos'=>$documentos
              );        
        }      
     
        return  $array; 
	}
}
