<?php

namespace PiedraBundle\Repository;

/**
 * DominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DominioRepository extends \Doctrine\ORM\EntityRepository
{
}
