<?php

namespace PiedraBundle\Repository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{

	
	/*
	* obtener listado de correo sin asignar
	*/
	public function getEmailSinAsignar(){

		$em= $this->getEntityManager();       
     
        $email_sinAsignar = 'SELECT e.id, e.email FROM PiedraBundle:Email e WHERE e.id NOT IN (SELECT e1.id FROM PiedraBundle:UsuarioDominio ud JOIN ud.email e1 WHERE ud.baja =:baja) ';
        $email_sinAsignar = $em->createQuery($email_sinAsignar); 
        return $email_sinAsignar        			
        			->setParameter('baja', true)
        			->getResult();        
	}
}
