<?php

namespace PiedraBundle\Repository;

/**
 * ListNomUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListNomUserRepository extends \Doctrine\ORM\EntityRepository
{
}
