<?php

namespace PiedraBundle\Repository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoRepository extends \Doctrine\ORM\EntityRepository
{
}
