<?php

namespace PiedraBundle\Repository;

/**
 * PasswordSetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordSetupRepository extends \Doctrine\ORM\EntityRepository
{

	


}
