<?php

namespace PiedraBundle\Repository;

/**
 * PcListNomUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcListNomUserRepository extends \Doctrine\ORM\EntityRepository
{
}
