<?php

namespace PiedraBundle\Repository;

/**
 * PcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcRepository extends \Doctrine\ORM\EntityRepository
{


	public function getPcsInventario($dept){
        $em= $this->getEntityManager();

        $dql ='SELECT p.id, p.nombrePc, d.nombre FROM PiedraBundle:Pc p JOIN p.departamento d WHERE p.departamento =:dept';
        $pcs = $em->createQuery($dql);
        $pcs = $pcs->setParameter('dept', $dept)->getResult();         

        $pcsInventario = array();

        foreach ($pcs as $pc) {
        	$dql ='SELECT i FROM PiedraBundle:Inventario i JOIN i.pc p WHERE p.id =:pc and i.baja=:false';
	        $inventario_pc = $em->createQuery($dql);
	        $inventario_pc = $inventario_pc
                                ->setParameter('pc', $pc['id'])
                                ->setParameter('false', 0)
                                ->getResult();

	        $pcsInventario[] = array(	
                'pc' => $pc,        	
	        	'inventario' =>$inventario_pc
	        );
            
        }

        return $pcsInventario;

    }

    /*
    * pcs del departamento selecionado
    */
    public function getPcsDepartamento($dept){

        $em= $this->getEntityManager();

        $dql ='SELECT p.id, p.nombrePc FROM PiedraBundle:Pc p Where p.departamento=:dept';
        $pcs = $em->createQuery($dql);
        $pcs = $pcs->setParameter('dept', $dept)->getResult(); 

        return $pcs;
    }





    /////////////******* FUNCIONES COMPLEMENTARIAS ************//////////////

    /*
    * convierte arreglo en listata string para select
    */
    public function listaString($listado){

        $list = "{"; $cont = 0;
        foreach ($listado as $lista) {

            $cont++;
            if($cont == count($listado)){
                $list .= '"'.$lista->getId().'": "'.$lista->getNombrePc().'"}';
            }else{
                $list .= '"'.$lista->getId().'": "'.$lista->getNombrePc().'",';
            }            
         } 


        return $list;
    }


}
