<?php

namespace PiedraBundle\Repository;

/**
 * PcUsuarioDominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcUsuarioDominioRepository extends \Doctrine\ORM\EntityRepository
{
}
