<?php

namespace PiedraBundle\Repository;

/**
 * SistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* obtener listado sistema: $baja = true los activos, $baja = false las baja
	*/	
	public function getSistemas($baja){
		$em= $this->getEntityManager();
        $dql ='SELECT s FROM PiedraBundle:Sistema s JOIN s.usuarioDominio ud WHERE ud.baja=:baja';
        $dql = $em->createQuery($dql); 
        return $dql->setParameter('baja', $baja)->getResult();      
	}


}
