<?php

namespace PiedraBundle\Repository;

/**
 * UsuarioDominioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioDominioRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	* obtener listado usuario daminio $baja = true los activos, $baja = false las baja
	*/	
	public function getUsuarioDominio($baja){
		$em= $this->getEntityManager();
        $dql ='SELECT ud FROM PiedraBundle:UsuarioDominio ud Join ud.cargo c WHERE ud.baja=:baja Order by c.cargo Asc';
        $dql = $em->createQuery($dql); 
        return $dql->setParameter('baja', $baja)->getResult();      
	}

	

	/*
	* obtener usuario del cargo director adjunto
	*/	
	public function getUsuarioDominiocargoDirAdj(){
		$em= $this->getEntityManager();
        $dql ='SELECT ud FROM PiedraBundle:UsuarioDominio ud Join ud.cargo c WHERE c.id = 7 and ud.baja=:baja';
        $dql = $em->createQuery($dql); 
        return $dql->setParameter('baja',1)->getResult();      
	}


	/*
	* obtener  usuario del cargo informatico
	*/	
	public function getUsuarioDominiocargoInformatico(){
		$em= $this->getEntityManager();
        $dql ='SELECT ud FROM PiedraBundle:UsuarioDominio ud Join ud.cargo c WHERE c.id = 8 and ud.baja=:baja';
        $dql = $em->createQuery($dql); 
        return $dql->setParameter('baja',1)->getResult();      
	}

	
}
