<?php

namespace Proxies\__CG__\InformaticaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipo extends \InformaticaBundle\Entity\Equipo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'imagen', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'tipoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'responsable', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'equipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'medioBasico', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'noSubmayor', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'baja', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'realizadopor', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'sello', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'estadoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'nombreEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'unidad'];
        }

        return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'imagen', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'tipoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'responsable', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'equipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'medioBasico', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'noSubmayor', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'baja', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'fecha', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'realizadopor', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'sello', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'estadoEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'observacion', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'nombreEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\Equipo' . "\0" . 'unidad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedioBasico($medioBasico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedioBasico', [$medioBasico]);

        return parent::setMedioBasico($medioBasico);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedioBasico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedioBasico', []);

        return parent::getMedioBasico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoSubmayor($noSubmayor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoSubmayor', [$noSubmayor]);

        return parent::setNoSubmayor($noSubmayor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoSubmayor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoSubmayor', []);

        return parent::getNoSubmayor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaja($baja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaja', [$baja]);

        return parent::setBaja($baja);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaja', []);

        return parent::getBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealizadopor($realizadopor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealizadopor', [$realizadopor]);

        return parent::setRealizadopor($realizadopor);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealizadopor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealizadopor', []);

        return parent::getRealizadopor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSello($sello)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSello', [$sello]);

        return parent::setSello($sello);
    }

    /**
     * {@inheritDoc}
     */
    public function getSello()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSello', []);

        return parent::getSello();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEquipo(\InformaticaBundle\Entity\TipoEquipo $tipoEquipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEquipo', [$tipoEquipo]);

        return parent::setTipoEquipo($tipoEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEquipo', []);

        return parent::getTipoEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable(\InformaticaBundle\Entity\Responsable $responsable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoEquipo(\InformaticaBundle\Entity\EstadoEquipo $estadoEquipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoEquipo', [$estadoEquipo]);

        return parent::setEstadoEquipo($estadoEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoEquipo', []);

        return parent::getEstadoEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEquipo($nombreEquipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEquipo', [$nombreEquipo]);

        return parent::setNombreEquipo($nombreEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEquipo', []);

        return parent::getNombreEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(\InformaticaBundle\Entity\Imagen $imagen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidad(\InformaticaBundle\Entity\Unidad $unidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidad', [$unidad]);

        return parent::setUnidad($unidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidad', []);

        return parent::getUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipo(\InformaticaBundle\Entity\Equipo $equipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipo', [$equipo]);

        return parent::setEquipo($equipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipo', []);

        return parent::getEquipo();
    }

}
