<?php

namespace Proxies\__CG__\PiedraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sistema extends \PiedraBundle\Entity\Sistema implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'usuarioDominio', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunAcc', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunAft', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunUtil', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'aListar', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunPms', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunPos', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunStock', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunIcs', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'abacoNomina', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'habitat', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'sarh', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'sstt', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'reservas', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'compras', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'inHova', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'aInformatica'];
        }

        return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'usuarioDominio', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunAcc', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunAft', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunUtil', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'aListar', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunPms', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunPos', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunStock', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'zunIcs', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'abacoNomina', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'habitat', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'sarh', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'sstt', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'reservas', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'compras', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'inHova', '' . "\0" . 'PiedraBundle\\Entity\\Sistema' . "\0" . 'aInformatica'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sistema $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunAcc($zunAcc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunAcc', [$zunAcc]);

        return parent::setZunAcc($zunAcc);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunAcc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunAcc', []);

        return parent::getZunAcc();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunAft($zunAft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunAft', [$zunAft]);

        return parent::setZunAft($zunAft);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunAft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunAft', []);

        return parent::getZunAft();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunPms($zunPms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunPms', [$zunPms]);

        return parent::setZunPms($zunPms);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunPms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunPms', []);

        return parent::getZunPms();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunPos($zunPos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunPos', [$zunPos]);

        return parent::setZunPos($zunPos);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunPos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunPos', []);

        return parent::getZunPos();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunStock($zunStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunStock', [$zunStock]);

        return parent::setZunStock($zunStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunStock', []);

        return parent::getZunStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbacoNomina($abacoNomina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbacoNomina', [$abacoNomina]);

        return parent::setAbacoNomina($abacoNomina);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbacoNomina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbacoNomina', []);

        return parent::getAbacoNomina();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabitat($habitat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabitat', [$habitat]);

        return parent::setHabitat($habitat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitat', []);

        return parent::getHabitat();
    }

    /**
     * {@inheritDoc}
     */
    public function setSarh($sarh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSarh', [$sarh]);

        return parent::setSarh($sarh);
    }

    /**
     * {@inheritDoc}
     */
    public function getSarh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSarh', []);

        return parent::getSarh();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioDominio(\PiedraBundle\Entity\UsuarioDominio $usuarioDominio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioDominio', [$usuarioDominio]);

        return parent::setUsuarioDominio($usuarioDominio);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioDominio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioDominio', []);

        return parent::getUsuarioDominio();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunUtil($zunUtil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunUtil', [$zunUtil]);

        return parent::setZunUtil($zunUtil);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunUtil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunUtil', []);

        return parent::getZunUtil();
    }

    /**
     * {@inheritDoc}
     */
    public function setAListar($aListar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAListar', [$aListar]);

        return parent::setAListar($aListar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAListar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAListar', []);

        return parent::getAListar();
    }

    /**
     * {@inheritDoc}
     */
    public function setSstt($sstt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSstt', [$sstt]);

        return parent::setSstt($sstt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSstt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSstt', []);

        return parent::getSstt();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservas($reservas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservas', [$reservas]);

        return parent::setReservas($reservas);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservas', []);

        return parent::getReservas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompras($compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompras', [$compras]);

        return parent::setCompras($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompras', []);

        return parent::getCompras();
    }

    /**
     * {@inheritDoc}
     */
    public function setInHova($inHova)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInHova', [$inHova]);

        return parent::setInHova($inHova);
    }

    /**
     * {@inheritDoc}
     */
    public function getInHova()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInHova', []);

        return parent::getInHova();
    }

    /**
     * {@inheritDoc}
     */
    public function setAInformatica($aInformatica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAInformatica', [$aInformatica]);

        return parent::setAInformatica($aInformatica);
    }

    /**
     * {@inheritDoc}
     */
    public function getAInformatica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAInformatica', []);

        return parent::getAInformatica();
    }

    /**
     * {@inheritDoc}
     */
    public function setZunIcs($zunIcs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZunIcs', [$zunIcs]);

        return parent::setZunIcs($zunIcs);
    }

    /**
     * {@inheritDoc}
     */
    public function getZunIcs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZunIcs', []);

        return parent::getZunIcs();
    }

}
