<?php

namespace Proxies\__CG__\InformaticaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EquipoCuadradoAFT extends \InformaticaBundle\Entity\EquipoCuadradoAFT implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'ctipoequipo', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'responsable', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'numeroinventarioEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'numeroInventarioPP', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'descSubmayor', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'localizacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'id', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'ctipoequipo', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'responsable', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'numeroinventarioEquipo', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'numeroInventarioPP', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'descSubmayor', '' . "\0" . 'InformaticaBundle\\Entity\\EquipoCuadradoAFT' . "\0" . 'localizacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EquipoCuadradoAFT $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtipoequipo($ctipoequipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtipoequipo', [$ctipoequipo]);

        return parent::setCtipoequipo($ctipoequipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtipoequipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtipoequipo', []);

        return parent::getCtipoequipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable($responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroinventarioEquipo($numeroinventarioEquipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroinventarioEquipo', [$numeroinventarioEquipo]);

        return parent::setNumeroinventarioEquipo($numeroinventarioEquipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroinventarioEquipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroinventarioEquipo', []);

        return parent::getNumeroinventarioEquipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroInventarioPP($numeroInventarioPP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroInventarioPP', [$numeroInventarioPP]);

        return parent::setNumeroInventarioPP($numeroInventarioPP);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroInventarioPP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroInventarioPP', []);

        return parent::getNumeroInventarioPP();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescSubmayor($descSubmayor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescSubmayor', [$descSubmayor]);

        return parent::setDescSubmayor($descSubmayor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescSubmayor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescSubmayor', []);

        return parent::getDescSubmayor();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalizacion($localizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalizacion', [$localizacion]);

        return parent::setLocalizacion($localizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalizacion', []);

        return parent::getLocalizacion();
    }

}
