<?php

namespace Proxies\__CG__\PiedraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inventario extends \PiedraBundle\Entity\Inventario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'departamento', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'pc', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'componente', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'marca', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'modelo', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'serial', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'estado', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'medioBasico', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'noSubmayor', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'baja', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'observacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'departamento', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'pc', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'componente', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'marca', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'modelo', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'serial', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'estado', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'medioBasico', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'noSubmayor', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'baja', '' . "\0" . 'PiedraBundle\\Entity\\Inventario' . "\0" . 'observacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inventario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', [$marca]);

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', []);

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', [$modelo]);

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', []);

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial($serial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', [$serial]);

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', []);

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedioBasico($medioBasico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedioBasico', [$medioBasico]);

        return parent::setMedioBasico($medioBasico);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedioBasico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedioBasico', []);

        return parent::getMedioBasico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoSubmayor($noSubmayor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoSubmayor', [$noSubmayor]);

        return parent::setNoSubmayor($noSubmayor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoSubmayor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoSubmayor', []);

        return parent::getNoSubmayor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento(\PiedraBundle\Entity\Departamento $departamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', [$departamento]);

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', []);

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPc(\PiedraBundle\Entity\Pc $pc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPc', [$pc]);

        return parent::setPc($pc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPc', []);

        return parent::getPc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaja($baja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaja', [$baja]);

        return parent::setBaja($baja);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaja', []);

        return parent::getBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setComponente(\PiedraBundle\Entity\Componente $componente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComponente', [$componente]);

        return parent::setComponente($componente);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponente', []);

        return parent::getComponente();
    }

}
