<?php

namespace Proxies\__CG__\PiedraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Documento extends \PiedraBundle\Entity\Documento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'nombreDoc', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'descripcion', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'urlArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'extArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'imgArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'fecha', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'organismo'];
        }

        return ['__isInitialized__', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'nombreDoc', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'descripcion', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'urlArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'extArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'imgArchivo', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'fecha', '' . "\0" . 'PiedraBundle\\Entity\\Documento' . "\0" . 'organismo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Documento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDoc($nombreDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDoc', [$nombreDoc]);

        return parent::setNombreDoc($nombreDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDoc', []);

        return parent::getNombreDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlArchivo($urlArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlArchivo', [$urlArchivo]);

        return parent::setUrlArchivo($urlArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlArchivo', []);

        return parent::getUrlArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtArchivo($extArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtArchivo', [$extArchivo]);

        return parent::setExtArchivo($extArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtArchivo', []);

        return parent::getExtArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgArchivo($imgArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgArchivo', [$imgArchivo]);

        return parent::setImgArchivo($imgArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgArchivo', []);

        return parent::getImgArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganismo(\PiedraBundle\Entity\Organismo $organismo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganismo', [$organismo]);

        return parent::setOrganismo($organismo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganismo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganismo', []);

        return parent::getOrganismo();
    }

}
